# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/
variables:
  VM_IMAGE: macOS-12
  XCODE_VERSION: 13.4
  PLATFORM_VERSION: 15.5
  DEVICE_NAME: iPhone 12
  DEFAULT_NODE_VERSION: "16.x"

pool:
  vmImage: "$(VM_IMAGE)"

stages:
- stage: Unit_Tests_And_Linters
  jobs:
  - job: Node_Unit_Tests
    steps:
    - template: azure-templates/node_setup_steps.yml
    - script: |
        npm install -g appium@next
        npm install
    - script: npm run test

- stage: Integration_Tests
  jobs:
  - job: Node_Integration_Tests
    variables:
      CI: true
      _FORCE_LOGS: 1
    steps:
    - template: azure-templates/node_setup_steps.yml
    - script: |
        npm install -g appium@next
        npm install
        appium driver install --source=local .
    - script: npm run e2e-test
