# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/
variables:
  VM_IMAGE: macOS-10.15
  XCODE_VERSION: 12.1
  PLATFORM_VERSION: 14.1
  DEVICE_NAME: iPhone 11 Pro Max
  DEFAULT_NODE_VERSION: "12.x"

pool:
  vmImage: "$(VM_IMAGE)"

stages:
- stage: Unit_Tests_And_Linters
  jobs:
  - job: Node_Unit_Tests
    steps:
    - template: azure-templates/node_setup_steps.yml
    - script: npm install
    - script: npm run test

- stage: Integration_Tests
  jobs:
  - job: Node_Integration_Tests
    variables:
      CI: true
      _FORCE_LOGS: 1
    steps:
    - template: azure-templates/node_setup_steps.yml
    - script: npm install
    - script: npm run e2e-test
